### ISSUE TITLE
关于渲染速度

### ISSUE THREAD

**Issue by cryer** [naeioi/PBF-CUDA#1]
作者您好，我想问一下，我在知乎上看到视频中iter为4渲染速度也蛮快的，我笔记本1050Ti 设置iter为1都比你那个慢很多，可以问下您的电脑配置吗？或者说我这里是不是还有除了配置以外的问题，还有什么改进方法？因为我还没有研究代码，只把最大粒子数量缩小到5万，还是一样的慢。

**Comment by naeioi** [comment]
您好，谢谢你的关注。1050Ti理应能应付30w粒子的实时渲染。您的编译模式调整到Release了吗？

**Comment by cryer** [comment]
哈哈，忘了一直在debug模式，后来试了release，发现nanogui的windows.cpp 36行一直报内存错误，读取位置 0xFFFFFFFFFFFFFFFF 时发生访问冲突，解决了一会还是这个错误，就把release的优化选项关了，就可以运行了，优化关了速度还是比我原来快很多很多。。我也没想到差距会这么大。。谢谢大佬了

**Comment by naeioi** [comment]
不客气。

**Comment by DanSon3** [comment]
我想问下作者，怎么编译的时候一直提示GLuint这些变量未声明

**Comment by Sycamore-Ma** [comment]
Hello, I was trying to do some paper reproduction based on your project recently, but some configurations needed to be fixed about NanoGUI when I tried to compile your project. Does your NanoGUI dependency work correctly in your local environment? Have you made any other external references globally?
